Repository ssi-dk/diseasystore, pull requests merged in 2024-03, with the labels that each got.

#122 Add default value to diseasyoption
  DESCRIPTION
  NEWS.md
  R/0_R6_utils.R
  R/DiseasystoreGoogleCovid19.R
  inst/WORDLIST
  man/diseasyoption.Rd
  man/diseasystore-package.Rd
  tests/testthat/test-0_R6_utils.R
  tests/testthat/test-DiseasystoreGoogleCovid19.R
  vignettes/diseasystore.Rmd
Labels: enhancement

#126 docs(README): fix spelling
  README.Rmd
  README.md
Labels: documentation

#111 Add tests on SQL Server back ends
  .github/workflows/R-CMD-check.yaml
  .github/workflows/all-workflows.yaml
  .github/workflows/code-coverage.yaml
  DESCRIPTION
  R/0_locks.R
  R/DiseasystoreBase.R
  R/truncate_interlace.R
  tests/testthat/helper-setup.R
  tests/testthat/setup.R
  tests/testthat/test-DiseasystoreBase.R
  tests/testthat/test-DiseasystoreGoogleCovid19.R
  tests/testthat/test-SCDB_messages.R
  tests/testthat/test-drop_diseasystore.R
Labels: enhancement

#123 Add a testing suite for diseasystores
  NAMESPACE
  NEWS.md
  R/3_feature_store_helpers.R
  R/DiseasystoreBase.R
  R/test_diseasystore.R
  cran-comments.md
  man/age_labels.Rd
  man/available_diseasystores.Rd
  man/diseasystore_exists.Rd
  man/get_diseasystore.Rd
  man/test_diseasystore.Rd
  man/to_diseasystore_case.Rd
  tests/testthat/test-DiseasystoreGoogleCovid19.R
  vignettes/extending-diseasystore.Rmd
Labels: enhancement

#121 Improve table identification
  NEWS.md
  R/DiseasystoreBase.R
  R/drop_diseasystore.R
  inst/WORDLIST
  tests/testthat/test-drop_diseasystore.R
Labels: bug, enhancement

#119 chore: synced file(s) with ssi-dk/AEF-DDF
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/sync_reverse.yaml
  .github/templates/README_template.Rmd
  .github/workflows/all-workflows.yaml
  .github/workflows/synchronise-files.yaml
  DESCRIPTION
  README.md
  pak.lock
  tests/testthat/helper-setup.R
  tests/testthat/test-0_linters.R
Labels: sync
